/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fb0ef0b5-f434-4bc7-a5d0-9040961c10bc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u6lNOgEZI",
    "aws_user_pools_web_client_id": "1grmdpmutk4djevkvi7s6osm3i",
    "oauth": {}
};


export default awsmobile;
